server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: school-service.microservices.svc
    healthcheck:
      enabled: true
    lease:
      duration: 5
    registerWithEureka: true

spring:
  application:
    name: school-service

logging:
  level:
    com.example.howtodoinjava: DEBUG
