server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://eureka.microservices.svc:8761/eureka
      
      instance:
      hostname: school-service
    healthcheck:
      enabled: true
    lease:
      duration: 5
    registerWithEureka: true

spring:
  application:
    name: school-service

logging:
  level:
    com.example.howtodoinjava: DEBUG
