server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: http://eureka-microservices.apps.cdeocp.com 
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
