server:
  port: 8098

eureka:
  instance:
    #hostname: student-service-microservices.apps.cdeocp.com
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #preferIpAddress: false
  client:
    availabilityZones: 
      default: http://student-service-microservices.apps.cdeocp.com
    serviceUrl:
      defaultZone: http://eureka-microservices.apps.cdeocp.com/eureka
      
      
    healthcheck:
      enabled: true
    lease:
      duration: 5
    registerWithEureka: true

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG
