server:
  port: 8098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
  client:
    serviceUrl:
      defaultZone: student-service.microservices.svc
    healthcheck:
      enabled: true
    lease:
      duration: 5
    registerWithEureka: true

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG
