server:
  port: 8098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #preferIpAddress: false
  client:
    name: student-service
    vipAddress: http://student-service-microservices.apps.cdeocp.com
    serviceUrl:
      defaultZone: http:eureka.microservices.svc:8761/eureka
      
      
    healthcheck:
      enabled: true
    lease:
      duration: 5
    registerWithEureka: true

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG
